### Essential functions for solving ambiguity in posterior samples


# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

msf <- function(lambda, pivot) {
  .Call(`_infinitefactor_msf`, lambda, pivot)
}

jointRot = function(lambda, eta){
  ### solve rotational ambiguity via varimax
  vari = lapply(lambda, varimax)
  loads = lapply(vari, `[[`, 1)
  rots = lapply(vari, `[[`, 2)
  rotfact = mapply(`%*%`, eta, rots, SIMPLIFY = FALSE)
  
  norms = sapply(loads, norm, "2")
  piv = loads[order(norms)][[round(length(lambda)/2)]]
  
  matches = lapply(loads, msfOUT, piv)
  
  lamout = mapply(aplr, loads, matches, SIMPLIFY = FALSE)
  etaout = mapply(aplr, rotfact, matches, SIMPLIFY = FALSE)
  
  return(list(lambda = lamout, eta = etaout))
}

